"""
This script is to be ran in the django shell (python manage.py shell)

"""

from verbs.models import Verb

english_to_french = {
    "be": "être",
    "have": "avoir",
    "do": "faire",
    "would": "voudrait",
    "will": "vouloir",
    "can": "pouvoir",
    "know": "savoir",
    "see": "voir",
    "may": "pouvoir",
    "should": "devoir",
    "get": "obtenir",
    "think": "penser",
    "go": "aller",
    "make": "faire",
    "must": "devoir",
    "take": "prendre",
    "come": "venir",
    "say": "dire",
    "put": "mettre",
    "want": "vouloir",
    "give": "donner",
    "look": "regarder",
    "find": "trouver",
    "need": "avoir besoin",
    "like": "aimer",
    "set": "régler",
    "use": "utiliser",
    "become": "devenir",
    "tell": "dire",
    "keep": "garder",
    "help": "aider",
    "work": "travailler",
    "let": "laisser",
    "feel": "ressentir",
    "provide": "fournir",
    "believe": "croire",
    "try": "essayer",
    "shall": "devoir",
    "ask": "demander",
    "remember": "se souvenir",
    "leave": "partir",
    "show": "montrer",
    "pay": "payer",
    "run": "courir",
    "read": "lire",
    "seem": "sembler",
    "include": "inclure",
    "bring": "apporter",
    "understand": "comprendre",
    "start": "commencer",
    "play": "jouer",
    "cut": "couper",
    "live": "vivre",
    "meet": "rencontrer",
    "move": "bouger",
    "hear": "entendre",
    "call": "appeler",
    "stop": "arrêter",
    "turn": "tourner",
    "talk": "parler",
    "buy": "acheter",
    "thank": "remercier",
    "change": "changer",
    "continue": "continuer",
    "consider": "considérer",
    "allow": "permettre",
    "hope": "espérer",
    "produce": "produire",
    "stay": "rester",
    "appear": "apparaître",
    "write": "écrire",
    "hold": "tenir",
    "expect": "attendre",
    "ensure": "assurer",
    "suppose": "supposer",
    "wish": "souhaiter",
    "carry": "porter",
    "follow": "suivre",
    "offer": "offrir",
    "support": "soutenir",
    "accept": "accepter",
    "speak": "parler",
    "lead": "mener",
    "remain": "rester",
    "stand": "tenir",
    "suggest": "suggérer",
    "hit": "frapper",
    "develop": "développer",
    "happen": "arriver",
    "sit": "s'asseoir",
    "win": "gagner",
    "love": "aimer",
    "add": "ajouter",
    "learn": "apprendre",
    "create": "créer",
    "let's": "allons",
    "agree": "être d'accord",
    "apply": "appliquer",
    "wait": "attendre",
    "avoid": "éviter",
    "send": "envoyer",
    "form": "former",
    "explain": "expliquer",
    "return": "retourner",
    "sell": "vendre",
    "receive": "recevoir",
    "open": "ouvrir",
    "begin": "commencer",
    "eat": "manger",
    "increase": "augmenter",
    "voice": "exprimer",
    "spend": "dépenser",
    "join": "rejoindre",
    "reduce": "réduire",
    "save": "sauver",
    "require": "exiger",
    "fall": "tomber",
    "mind": "faire attention",
    "build": "construire",
}



for k,v in english_to_french.items():
    Verb(francais=v, anglais=k).save()

