# Generated by Django 5.0.4 on 2024-05-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('verbs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Verb',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('francais', models.CharField(max_length=50)),
                ('anglais', models.CharField(max_length=50)),
            ],
        ),
    ]
